meta_product_name: "A Brand A Score"
meta_title: "A Brand A Score - Find out brand scores for an eco-friendly and qualitative wardrobe"
meta_description: "A Brand A Score rates the social and environmental impact and the quality of famous brands"
meta_image: "photo-1.jpg" # should exist in `app/assets/images/`
twitter_account: "@a_brand_a_score_twitter_account"   # required for Twitter Cards
